language: android
dist: trusty
sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-28
  licenses:
   - 'android-sdk-license-.+'

before_script:
  - echo no | android create avd --force -n test -t android-28 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator