language: android
dist: trusty
sudo: false

android:
  components:
    - build-tools-28.0.3
    - android-28
  licenses:
   - 'android-sdk-license-.+'
   
script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build