swagger: '2.0'
info:
  description: >-
    This is a sample server Petstore server. You can find out more about Swagger
    at [http://swagger.io](http://swagger.io) or on [irc.freenode.net,
    #swagger](http://swagger.io/irc/). For this sample, you can use the api key
    `special-key` to test the authorization filters.
  version: 1.0.0
  title: Swagger GoodReadsApi
  termsOfService: 'http://swagger.io/terms/'
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
host: goodreads.com
schemes:
  - https
paths:
  /search/index.xml:
    get:
      summary: 'Find books by title, author, or ISBN'
      description: >-
        Get an xml response with the most popular books for the given query.
        This will search all books in the title/author/ISBN fields and show
        matches, sorted by popularity on Goodreads. There will be cases where a
        result is shown on the Goodreads site, but not through the API. This
        happens when the result is an Amazon-only edition and we have to honor
        Amazon's terms of service.
      operationId: queryBooks
      produces:
        - application/xml
      parameters:
        - name: q
          in: query
          description: >-
            The query text to match against book title, author, and ISBN fields.
            Supports boolean operators and phrase searching.
          type: string
        - name: page
          in: query
          description: 'Which page to return (default 1, optional)'
          type: integer
        - name: key
          required: true
          in: query
          description: Developer key
          type: string
        - name: 'search[field]'
          in: query
          description: >-
            Field to search, one of 'title', 'author', or 'all' (default is
            'all')
          type: string
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/GoodReadsResponse'
        '400':
          description: Invalid status value
securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
definitions:
  Author:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  Book:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      author:
        $ref: '#/definitions/Author'
      image_url:
        type: string
      small_image_url:
        type: string
  Work:
    type: object
    properties:
      id:
        type: integer
        format: int64
      books_count:
        type: integer
        format: int64
      ratings_count:
        type: integer
        format: int64
      text_reviews_count:
        type: integer
        format: int64
      original_publication_year:
        type: integer
        format: int64
      original_publication_month:
        type: integer
        format: int64
      original_publication_day:
        type: integer
        format: int64
      average_rating:
        type: number
      best_book:
        $ref: '#/definitions/Book'
    xml:
      name: work
  Search:
    type: object
    properties:
      query:
        type: string
      results-start:
        type: integer
        format: int64
      results-end:
        type: integer
        format: int64
      total-results:
        type: integer
        format: int64
      source:
        type: string
      query-time-seconds:
        type: number
      results:
        type: array
        items:
          $ref: '#/definitions/Work'
        xml:
          wrapped: true
  Request:
    type: object
    properties:
      authentication:
        type: boolean
      key:
        type: string
      method:
        type: string
  GoodReadsResponse:
    type: object
    properties:
      Request:
        $ref: '#/definitions/Request'
      search:
        $ref: '#/definitions/Search'
externalDocs:
  description: Find out more about Swagger
  url: 'http://swagger.io'
